name: CI-macOS

# Controls when the action will run.
# Triggers the workflow on pull request events but only for the master branch.
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-latest

    timeout-minutes: 8

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: List root directory contents
      run: ls -al

    - name: List EssentialFeed directory contents
      run: ls -al EssentialFeed

    - name: Build and test
      run: |
        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild clean build test \
          -project EssentialFeed/EssentialFeed.xcodeproj \
          -scheme CI \
          CODE_SIGN_IDENTITY= \
          CODE_SIGNING_REQUIRED=NO \
          -sdk macosx \
          -destination platform=macOS \
          ONLY_ACTIVE_ARCH=YES
      env:
        IDEPackageSupportUseBuiltinSCM: YES
