name: CI-macOS-iOS

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IDEPackageSupportUseBuiltinSCM: YES
  CODE_SIGN_IDENTITY: ""
  CODE_SIGNING_REQUIRED: NO

jobs:
  build-and-test:
    runs-on: macOS 15
    timeout-minutes: 15
    strategy:
      matrix:
        platform: [macOS, iOS]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Cache Derived Data
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-xcode-${{ matrix.platform }}-${{ hashFiles('**/*.xcodeproj') }}

      - name: List root directory contents
        run: ls -al

      - name: List EssentialFeed directory contents
        run: ls -al EssentialFeed

      - name: Build and test ${{ matrix.platform }} target
        run: |
          set -o pipefail
          if [ "${{ matrix.platform }}" == "macOS" ]; then
            xcodebuild clean build test \
              -project EssentialFeed.xcodeproj \
              -scheme CI_macOS \
              -sdk macosx \
              -destination "platform=macOS,arch=x86_64" \
              ONLY_ACTIVE_ARCH=YES | tee xcodebuild-macOS.log
          else
            xcodebuild clean build test \
              -project EssentialFeed.xcodeproj \
              -scheme CI_iOS \
              -sdk iphonesimulator \
              -destination "platform=iOS Simulator,name=iPhone 15,OS=17.2" \
              ONLY_ACTIVE_ARCH=YES | tee xcodebuild-iOS.log
          fi

      - name: Archive Derived Data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: DerivedData-${{ matrix.platform }}
          path: ~/Library/Developer/Xcode/DerivedData

      - name: Archive Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-logs-${{ matrix.platform }}
          path: |
            xcodebuild-macOS.log
            xcodebuild-iOS.log
            ~/Library/Logs
